//word libraries
let common = [
	['week', '주'],
	['year', '년'],
	['today', '오늘'],
	['tomorrow', '내일'],
	['yesterday', '어제'],
	['small', '작은'],
	['to do', '하다'],
	['to be or to have', '있다'],
	['me or I', '나'],
	['we or our', '우리'],
	['person or human', '사람'],
	['to not exist, to be absent, or to not have', '없다'],
	['he', '그'],
	['no', '아니요'],
	['that thing over there', '저것'],
	['to see, watch, or look at', '보다'],
	['to go', '가다'],
	['work', '일'],
	['this', '이'],
	['to speak', '말하다'],
	['but, though, however, or nevertheless', '그러나'],
	['to come', '오다'],
	['to know', '알다'],
	['to be good', '좋다'],
	['house', '집'],
	['and', '그리고'],
	['she', '그녀'],
	['to eat', '먹다'],
	['a thing or object', '것'],
	['to not be or to not do', '않다'],
	['that thing', '거'],
	['to say', '말하다'],
	['mr./mrs.', '씨'],
	['to be big', '크다'],
	['problem', '문제'],
	['my', '나의'],
	['yes', '예'],
	['when', '언제'],
	['bathroom', '화장실'],
	['where', '어디'],
	['please', '주세요'],
	['what (did you say)?', '뭐?'],
	['slowly', '천천히'],
	['you', '너'],
	['who', '누구']
]
let commonPhrases = [
	['hello', '안녕하세요'],
	["I'm hungry", '배고파'],
	["excuse me (to get one's attention)", '잠시만요'],
	['thank you', '감사합니다'],
	['how are you?', '어떻게 지내세요?'],
	['long time no see', '오랜만이다'],
	['where are you from?', '어디서 오셨어요?'],
	['my name is ~name~', '제 이름은 ~name~ 입니다'],
	['where are you from?', '어디서 오셨어요?'],
	["I'm from ~location~", '저는 ~location~ 에서 왔어요'],
	['nice to meet you', '만나서 반갑습니다'],
	['good night (informal)', '잘자'],
	['really?', '진짜?'],
	['good luck', '행운을 빈다'],
	['cheers', '건배'],
	["I don't know", '몰라'],
	['I understand', '아랐어'],
	["I don't understand", '모르겠습니다'],
	['to see, watch, or look at', '보다'],
	['where is the bathroom?', '화장실이 어디예요?'],
	['I miss you', '보고싶다'],
	['I love you', '사랑해'],
	['do you speak English?', '영어 하세요?'],
	['please speak slowly', '천천히 말씀해 주세요'],
	['how much does it cost?', '얼마에요?'],
	['check, please', '계산해 주세요'],
	['just a moment', '잠깐만요'],
	['I hurt', '아파요'],
	["that's good", '좋아요'],
	['do you take credit cards?', '카드 돼요?'],
	['what is the wifi password?', '비밀 번호 알려 주세요?'],
	['please give me a discount', '좀 깎아 주세요'],
	['you can do it!', '잘할 수 있어요!'],
	["don't give up", '포기 하지마세요']
]
let magic = [
	['warning', '경고'],
	['game loss', '게임패'],
	['match loss', '매치패'],
	['disqualification', '실격'],
	['game play error', '게임 플레이 오류'],
	['looking at extra cards', '격발능력 놓침'],
	['hidden card error', '숨겨진 카드 오류'],
	['mulligan procedure error', '멀리건 절차 오류'],
	['game rule violation', '게임 규칙 위반'],
	['failure to maintain the game state', '게임 상태 유지 실패'],
	['tardiness', '지각'],
	['decklist problem', '덱리스트 문제'],
	['marked cards', '표시된 카드'],
	['cheating', '속임수'],
	['missed trigger', '격발능력 놓침'],
	['combat', '전투 단계'],
	['beginning of combat', '전투시작단'],
	['declare attackers', '공격자선언단'],
	['declare blockers', '방어자선언단'],
	['damage step', '전투피해단'],
	['counter a spell', '주문 무효화하기']
]